### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by jayhpark99** [jayhpark99/Pipergram#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create an account and it will be saved to the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-20 at 3 05 54 PM](https://user-images.githubusercontent.com/90732703/146844438-5b3c01c7-1a03-461e-870d-77d6dd0b8258.png)
![Screen Shot 2021-12-20 at 3 05 45 PM](https://user-images.githubusercontent.com/90732703/146844436-71127396-60df-495b-9cab-efa836e4178c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [x] Update `schema.sql` to create a table named "users"

### ☁️ Server
- [x] Update `server/index.js` to receive request from client and hash the password with argon2 then run a query for the database to insert the user data
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Create a component to accept user input and send request to server

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
