### ISSUE TITLE
Feature: User can log in

### ISSUE THREAD

**Issue by jayhpark99** [jayhpark99/Pipergram#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user inputs a correct username and password, they will be able to log in and stay logged in.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-12-21 at 3 17 04 PM](https://user-images.githubusercontent.com/90732703/147009939-22291776-b560-449e-84f1-80e525225ebe.png)
![Screen Shot 2021-12-21 at 3 17 33 PM](https://user-images.githubusercontent.com/90732703/147009941-492aea79-253c-407b-a1e6-346603653f8d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ☁️ Server

- [x] Update `server/index.js` to receive requests and check if there is a matching combination in the database
- [x] if there is, send client a 200
- [x] if not, throw an error
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update component to allow the user to attempt to log in and send a request to the server with the inputs
- [x] if server sends 200, allow user to log in

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
